let birds = [
    {'name': 'Channel-billed Cuckoo', 'location': ['Australia'], 'photos': [{'src': '/BirdifiedGenius/images/channel-billed-cuckoo.jpg', 'credit': 'Paul Baife | Creative Commons BY 2.0', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/channel-billed-cuckoo-1.mp3', 'credit' : 'Marc Anderson | Creative Commons Attribution-NonCommercial-NoDerivs 4.0'},{'src':'/BirdifiedGenius/audio/channel-billed-cuckoo-2.mp3', 'credit' : 'Marc Anderson | Creative Commons Attribution-NonCommercial-NoDerivs 4.0'}], 'link': ''},
    {'name': 'Venezuelan Troupial', 'location': ['Caribbean', 'South America'], 'photos': [{'src':'/BirdifiedGenius/images/troupial.jpg', 'credit': 'Kati Fleming | Creative Commons BY 2.0', 'caption' : 'Text'}], 'sounds': [{'src':'/BirdifiedGenius/audio/venezuelan-troupial-1.mp3', 'credit': 'Marc Anderson | Creative Commons Attribution-NonCommercial-NoDerivs 4.0'},{'src':'/BirdifiedGenius/audio/venezuelan-troupial-2.mp3', 'credit' : 'Daniel Lane | Creative Commons Attribution-NonCommercial-ShareAlike 3.0'}], 'link': ''},
    {'name': 'Wild Turkey ', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/wild-turkey.jpg', 'credit' : 'Randy Fath | Unsplash', 'caption': 'A turkey'}], 'sounds': [{'src':'/BirdifiedGenius/audio/wild-turkey-1.mp3', 'credit': 'Mary Beth Stowe | Creative Commons Attribution-NonCommercial-NoDerivs 2.5'},{'src':'/BirdifiedGenius/audio/wild-turkey-2.mp3', 'credit': 'Andrew Spencer | Creative Commons Attribution-NonCommercial-NoDerivs 2.5'}], 'link': ''},
    {'name': 'Bald Eagle', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/bald-eagle.jpg', 'credit': 'Mathew Schwartz | Unsplash', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/bald-eagle-1.mp3', 'credit': 'Paul Marvin | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/bald-eagle-2.mp3', 'credit': 'Davyd Betchkal | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/bald-eagle-3.mp3', 'credit': 'Paul Marvin | Creative Commons Attribution-NonCommercial-ShareAlike 3.0'}], 'link': ''},
    {'name': 'Northern Cardinal', 'location': ['North America', 'Minnesota'], 'photos': [{'src': '/BirdifiedGenius/images/cardinal.jpg', 'credit': 'Lewis Meyers | Unsplash', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/cardinal-1.mp3', 'credit': 'Brian Hendrix | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}, {'src':'/BirdifiedGenius/audio/cardinal-2.mp3', 'credit': 'Juan Carlos Pérez Magaña | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/cardinal-3.mp3', 'credit': 'Scott Crabtree | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'Blue Jay', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/blue-jay.jpg', 'credit': 'Mathew Schwartz | Unsplash', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/blue-jay-1.mp3', 'credit': 'William Whitehead | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/blue-jay-2.mp3', 'credit': 'William Whitehead | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/blue-jay-3.mp3', 'credit': 'Frank Lambert | Creative Commons Attribution-NonCommercial-NoDerivs 4.0'}], 'link': ''},
    {'name': 'Common Grackle', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/common-grackle.jpg', 'credit': 'Jok2000 | Creative Commons BY 3.0', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/common-grackle-1.mp3', 'credit': 'Ted Floyd | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/common-grackle-2.mp3', 'credit': 'Russ Wigh | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/common-grackle-3.mp3', 'credit': 'Ted Floyd | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'Black-capped Chickadee', 'location': ['North America', 'Minnesota'], 'photos': [{'src': '/BirdifiedGenius/images/black-capped-chickadee.jpg', 'credit': 'Amanda Frank | Unsplash', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/black-capped-chickadee-1.mp3', 'credit': 'Ted Floyd | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/black-capped-chickadee-2.mp3', 'credit': 'Thomas Magarian | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'Hooded Merganser', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/hooded-merganser-1.jpg', 'credit': 'Ken Billington Creative Commons BY-SA 3.0', 'caption': ''}, {'src':'/BirdifiedGenius/images/hooded-merganser-2.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/hooded-merganser-1.mp3', 'credit': 'Andrew Spencer | Creative Commons Attribution-NonCommercial-NoDerivs 2.5'},{'src':'/BirdifiedGenius/audio/hooded-merganser-2.mp3', 'credit': 'Jim Berry | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'Common Loon', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/common-loon.jpg', 'credit': 'Kevin Crosby | Unsplash', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/common-loon-1.mp3', 'credit': 'Bruce Lagerquist | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/common-loon-2.mp3', 'credit': 'Fernand DEROUSSEN | Creative Commons Attribution-NonCommercial-NoDerivs 3.0'},{'src':'/BirdifiedGenius/audio/common-loon-3.mp3', 'credit': 'Bruce Lagerquist | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'Cooper\'s Hawk', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/coopers-hawk.jpg', 'credit': 'Mike\'s Birds | Creative Commons BY-SA 2.0', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/coopers-hawk-1.mp3', 'credit': 'Bruce Lagerquist | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}, {'src':'/BirdifiedGenius/audio/coopers-hawk-2.mp3', 'credit': 'Jim Holmes | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/coopers-hawk-3.mp3', 'credit': 'Paul Marvin | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'Red-tailed Hawk', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/red-tailed-hawk-1.jpg', 'credit': 'Rhododendrites | CC BY-SA 4.0', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/red-tailed-hawk-1.mp3', 'credit': 'Manuel Grosselet | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'},{'src':'/BirdifiedGenius/audio/red-tailed-hawk-2.mp3', 'credit': 'Bruce Lagerquist | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'African Pygmy Goose', 'location': ['Africa'], 'photos': [{'src':'/BirdifiedGenius/images/african-pygmy-goose-1.jpg', 'credit': 'Derek Keats | Creative Commons BY 2.0', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/african-pygmy-goose-1.mp3', 'credit': 'Andrew Spencer | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}, {'src':'/BirdifiedGenius/audio/african-pygmy-goose-2.mp3', 'credit': 'Andrew Spencer | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'African Sacred Ibis', 'location': ['Africa'], 'photos': [{'src':'/BirdifiedGenius/images/african-sacred-ibis-1.jpg', 'credit': 'Thomas Quine | CC BY 2.0', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/african-sacred-ibis-1.mp3', 'credit': 'Lynette Rudman | Creative Commons Attribution-NonCommercial-ShareAlike 4.0'}], 'link': ''},
    {'name': 'Australian Shelduck', 'location': ['Australia'], 'photos': [{'src':'/BirdifiedGenius/images/australian-shelduck-1.jpg', 'credit': 'Arpingstone | Public Domain', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/australian-shelduck-1.mp3', 'credit': 'Marc Anderson | Creative Commons Attribution-NonCommercial-NoDerivs 4.0'}, {'src':'/BirdifiedGenius/audio/australian-shelduck-2.mp3', 'credit': 'Marc Anderson | Creative Commons Attribution-NonCommercial-NoDerivs 3.0'}], 'link': ''},
]

// Photos and sounds are arrays, so the app could display any number of photos or sounds of the same bird
// This is mostly a proof of concept, so only a few birds have more than one option in these arrays
// Arrays are lists of objects to store credits and captions along with the src
