let birds = [
    {'name': 'Channel-billed Cuckoo', 'location': ['Australia'], 'photos': [{'src': '/BirdifiedGenius/images/channel-billed-cuckoo.jpg', 'credit': 'Photo: Paul Baife | CC BY 2.0', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/channel-billed-cuckoo-1.mp3'},{'src':'/BirdifiedGenius/audio/channel-billed-cuckoo-2.mp3'}], 'link': ''},
    {'name': 'Venezuelan Troupial', 'location': ['Caribbean', 'South America'], 'photos': [{'src':'/BirdifiedGenius/images/troupial.jpg', 'credit': 'Photo: Kati Fleming | CC BY 2.0', 'caption' : 'Text'}], 'sounds': [{'src':'/BirdifiedGenius/audio/venezuelan-troupial-1.mp3'},{'src':'/BirdifiedGenius/audio/venezuelan-troupial-2.mp3'}], 'link': ''},
    {'name': 'Wild Turkey ', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/wild-turkey.jpg', 'credit' : 'Photo: Randy Fath | Unsplash', 'caption': 'A turkey'}], 'sounds': [{'src':'/BirdifiedGenius/audio/wild-turkey-1.mp3'},{'src':'/BirdifiedGenius/audio/wild-turkey-2.mp3'}], 'link': ''},
    {'name': 'Bald Eagle', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/bald-eagle.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/bald-eagle-1.mp3'},{'src':'/BirdifiedGenius/audio/bald-eagle-2.mp3'},{'src':'/BirdifiedGenius/audio/bald-eagle-3.mp3'}], 'link': ''},
    {'name': 'Northern Cardinal', 'location': ['North America', 'Minnesota'], 'photos': [{'src': '/BirdifiedGenius/images/cardinal.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/cardinal-1.mp3'}, {'src':'/BirdifiedGenius/audio/cardinal-2.mp3'},{'src':'/BirdifiedGenius/audio/cardinal-3.mp3'}], 'link': ''},
    {'name': 'Blue Jay', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/blue-jay.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/blue-jay-1.mp3'},{'src':'/BirdifiedGenius/audio/blue-jay-2.mp3'},{'src':'/BirdifiedGenius/audio/blue-jay-3.mp3'}], 'link': ''},
    {'name': 'Common Grackle', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/common-grackle.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/common-grackle-1.mp3'},{'src':'/BirdifiedGenius/audio/common-grackle-2.mp3'},{'src':'/BirdifiedGenius/audio/common-grackle-3.mp3'}], 'link': ''},
    {'name': 'Black-capped Chickadee', 'location': ['North America', 'Minnesota'], 'photos': [{'src': '/BirdifiedGenius/images/black-capped-chickadee.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/black-capped-chickadee-1.mp3'},{'src':'/BirdifiedGenius/audio/black-capped-chickadee-2.mp3'}], 'link': ''},
    {'name': 'Hooded Merganser', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/hooded-merganser-1.jpg', 'credit': '', 'caption': ''}, {'src':'/BirdifiedGenius/images/hooded-merganser-2.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/hooded-merganser-1.mp3'},{'src':'/BirdifiedGenius/audio/hooded-merganser-2.mp3'}], 'link': ''},
    {'name': 'Common Loon', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/common-loon.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/common-loon-1.mp3'},{'src':'/BirdifiedGenius/audio/common-loon-2.mp3'},{'src':'/BirdifiedGenius/audio/common-loon-3.mp3'}], 'link': ''},
    {'name': 'Cooper\'s Hawk', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/coopers-hawk.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/coopers-hawk-1.mp3'}, {'src':'/BirdifiedGenius/audio/coopers-hawk-2.mp3'},{'src':'/BirdifiedGenius/audio/coopers-hawk-3.mp3'}], 'link': ''},
    {'name': 'Red-tailed Hawk', 'location': ['North America', 'Minnesota'], 'photos': [{'src':'/BirdifiedGenius/images/red-tailed-hawk-1.jpg', 'credit': '', 'caption': ''}], 'sounds': [{'src':'/BirdifiedGenius/audio/red-tailed-hawk-1.mp3'},{'src':'/BirdifiedGenius/audio/red-tailed-hawk-2.mp3'}], 'link': ''}
]

// Photos and sounds are arrays, so the app could display any number of photos or sounds of the same bird
// This is mostly a proof of concept, so only a few birds have more than one option in these arrays
// Arrays are lists of objects to store credits and captions along with the src
